name: Security Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Check HTML files
      run: |
        find . -name "*.html"

    - name: Check CSS files
      run: |
        find . -name "*.css"

    - name: Search for secrets
      run: |
        if grep -R \
          --exclude-dir=.git \
          --exclude-dir=.github \
          -E "password|apikey" .; then
            echo "Potential secret found!"
            exit 1
        fi

    - name: Validate CSP header
      run: |
        grep "Content-Security-Policy" index.html
